<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\RetailMedia.Core\RetailMedia.Core.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\RetailMedia.Messaging\RetailMedia.Messaging.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\RetailMedia.Web\RetailMedia.Web.csproj" />
    <ProjectReference Include="..\..\..\src\Infrastructure\RetailMedia.Infrastructure\RetailMedia.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>
</Project>
